/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_e09169b5 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/xsogqomyccqipsgvkauj/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
declare const Deno: {
  env: {
    get: (key: string) => string | undefined;
  };
};

// @ts-ignore Supabase Edge/Deno resolves jsr: specifiers at runtime.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => {
  const url = Deno.env.get("SUPABASE_URL");
  const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");

  if (!url || !serviceRoleKey) {
    throw new Error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
  }

  return createClient(url, serviceRoleKey);
};

// Set stores a key-value pair in the database.
export const set = async (key: string, value: unknown): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_e09169b5").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<unknown> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_e09169b5").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_e09169b5").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: unknown[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_e09169b5").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<unknown[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_e09169b5").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d: { value: unknown }) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_e09169b5").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<unknown[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_e09169b5").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d: { value: unknown }) => d.value) ?? [];
};