/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xsogqomyccqipsgvkauj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhzb2dxb215Y2NxaXBzZ3ZrYXVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwNTg4NTMsImV4cCI6MjA4ODYzNDg1M30.Fq-JrwXVkTY7BWhdp-SqINXF_Q9jbD34_jDXDkzjR_k"